baseURL = "https://ozkanpakdil.github.io/test-microservice-frameworks/"
title = "Microservice Framework Tests"
languageCode = "en-us"
# Use PaperMod via Hugo Modules
# When using modules, 'theme' can be set to the theme name (matching the imported module)
# rather than the repository path.
theme = "PaperMod"

# Use PaperMod via Hugo Modules (fetch theme automatically)
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
  # Ensure homepage lists posts whose Type is either "post" or "posts"
  mainSections = ["post", "posts"]

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]
  page = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

