baseURL = "https://ozkanpakdil.github.io/test-microservice-frameworks/"
title = "Microservice Framework Tests"
languageCode = "en-us"
# Use PaperMod via Hugo Modules
# When using modules, 'theme' can be set to the theme name (matching the imported module)
# rather than the repository path.
theme = "PaperMod"

[[menu.main]]
name = "Main Blog"
url = "https://ozkanpakdil.github.io/"
weight = 10

[[menu.main]]
name = "Home"
url = "/"
weight = 20

# Use PaperMod via Hugo Modules (fetch theme automatically)
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"

[params]
  # Ensure homepage lists posts whose Type is either "post" or "posts"
  mainSections = ["post", "posts"]

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS", "JSON"]
  page = ["HTML"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[pagination]
pagerSize = 7
enableInlineShortcodes = true
enableRobotsTXT = true
canonifyURLs = true
buildDrafts = false
buildFuture = false
buildExpired = false
enableEmoji = true
pygmentsUseClasses = true
mainsections = ["post", "posts", "pages", "projects", "wiki"]

[params.socialIcons]
[[params.socialIcons]]
name = "website"
url = "https://ozkanpakdil.github.io/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/ozkanpakdil"