version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: monthly
- package-ecosystem: maven
  directory: "/ktor"
  schedule:
    interval: "monthly"
  ignore:
    - dependency-name: "*"