name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v1.1.0
        with:
          github-token: "${{ secrets.TOKEN_GIT }}"
      - name: Enable auto-merge for Dependabot PRs
        if: ${{contains(steps.metadata.outputs.dependency-names, 'my-dependency') && steps.metadata.outputs.update-type == 'version-update:semver-patch'}}
        run: gh pr merge --auto --merge "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.TOKEN_GIT}}
#   auto-approve:
#     runs-on: ubuntu-latest
#     timeout-minutes: 30
#     steps:
#     - uses: hmarr/auto-approve-action@v2.0.0
#       if: github.actor == 'dependabot[bot]' || github.actor == 'dependabot-preview[bot]'
#       with:
#         github-token: "${{ secrets.TOKEN_GIT }}"
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        java: [11, 16]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Run jars and get test results
        run: ./runGatling.sh
      - name: Commit the test result
        run: |
          set -x
          DATE=$(date +"%Y-%m-%d")
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          rm -rf ozkanpakdil.github.io
          rm -rf page
          git clone https://${{ secrets.TOKEN_GIT }}@github.com/ozkanpakdil/ozkanpakdil.github.io.git page
          git config pull.rebase true
          mv test-result.md page/my_collections/_microservicetests/$DATE-microservice-framework-test-${{ matrix.java }}.markdown
          cd page/my_collections/_microservicetests/
          git add $DATE-microservice-framework-test-${{ matrix.java }}.markdown
          # ls -1tr | head -n -10 | xargs -d '\n' git rm -f --
          git commit -m "Automatic publish from micro frameworks test"
          git push
          cd ../../../
          rm -rf page
          # git pull --rebase
          if git branch | grep -q master; then
            if git status | grep -q modified; then
              git add README.md
              git commit -m "Automatic publish from micro frameworks test"
              git push -f 
            fi
          fi

