name: Java CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 11, 14 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Mvn build
      run: mvn test package|grep SUCCESS|grep s > README.md
    - name: Create size of jars table
      run: ls -lh */target/*.jar|awk '{print "|",$5,"|",$9}'
    - name: Run jars and get test results
      run: ./runGatling.sh
