name: Java CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [11, 14]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: Run jars and get test results
        run: ./runGatling.sh
      - name: Commit the test result
        run: |
          DATE=$(date +"%Y-%m-%d")
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git clone https://${{ secrets.TOKEN_GIT }}@github.com/ozkanpakdil/ozkanpakdil.github.io.git page
          # git config pull.rebase true
          mv test-result.md page/my_collections/_microservicetests/$DATE-microservice-framework-test-${{ matrix.java }}.markdown
          cd page
          git add my_collections/_microservicetests/$DATE-microservice-framework-test-${{ matrix.java }}.markdown
          git commit -m "Automatic publish from micro frameworks test"
          git pull --rebase
          git push
