name: Native CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        java: [17]
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          cache: 'maven'
          distribution: 'temurin'          
      - name: graalvm builds
        run: |
          gu install native-image
          mvn -ntp package -Pnative native:compile -DskipTests -f spring-boot-web/pom.xml
          mvn -ntp package -Pnative native:compile -DskipTests -f spring-boot-webflux/pom.xml
          mvn -ntp package -Pnative,native-image -Dpackaging=native-image -DskipTests -f quarkus/pom.xml
          mvn -ntp package -Pnative,native-image -Dpackaging=native-image -DskipTests -f micronaut/pom.xml
          mvn -ntp package -Pnative,native-image -Dpackaging=native-image -DskipTests -f ktor-demo/pom.xml
          mvn -ntp package -Pnative,native-image -Dpackaging=native-image -DskipTests -f helidon-se-netty/pom.xml
          mvn -ntp package -Pnative,native-image -Dpackaging=native-image -DskipTests -f vertx/pom.xml
          dotnet publish --configuration Release Dotnet6Microservice/
          dotnet publish --configuration Release Dotnet7Microservice/
      - name: native release packages
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          files: |
            ./quarkus/target/quarkus-demo-1.0.0-SNAPSHOT-runner
            ./micronaut/target/micronaut-demo
            ./spring-boot-web/target/springboot-demo-web
            ./spring-boot-webflux/target/springboot-webflux-demo
            ./vertx/target/vertx-demo
            ./helidon-se-netty/target/helidon-quickstart-se
            ./ktor-demo/target/ktor-demo
            ./Dotnet6Microservice/bin/Release/net6.0/publish/Dotnet6Microservice
            ./Dotnet7Microservice/bin/Release/net7.0/linux-x64/publish/Dotnet7Microservice
