name: Native CI

on:
  push:
    branches-ignore:
      - 'dependabot/**'
    paths:
      - '**/pom.xml'  # Only trigger if any pom.xml file is modified
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths:
      - '**/pom.xml'  # Only trigger if any pom.xml file is modified

permissions:
  contents: 'write'
  id-token: 'write'
  packages: 'write'
  deployments: 'write'
  repository-projects: 'write'
  pull-requests: 'write'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        java: [23]
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: ${{ matrix.java }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          distribution: 'graalvm'
      - name: graalvm builds
        run: |
          mvn -ntp package -Pnative native:compile -DskipTests -f spring-boot-web/pom.xml
          mvn -ntp package -Pnative native:compile -DskipTests -f spring-boot-webflux/pom.xml
          mvn -ntp package -Pnative,native-image -Dpackaging=native-image -DskipTests -f quarkus/pom.xml
          mvn -ntp package -Pnative,native-image -Dpackaging=native-image -DskipTests -f micronaut/pom.xml
          mvn -ntp package -Pnative,native-image -Dpackaging=native-image -DskipTests -f ktor-demo/pom.xml
          mvn -ntp package -Pnative,native-image -Dpackaging=native-image -DskipTests -f helidon-se-netty/pom.xml
          mvn -ntp package -Pnative,native-image -Dpackaging=native-image -DskipTests -f vertx/pom.xml

      - name: Extract Versions from pom.xml
        id: extract_versions
        run: |
          KTOR=$(grep -oPm1 "(?<=<ktor.version>)[^<]+" ktor-demo/pom.xml)
          KOTLIN=$(grep -oPm1 "(?<=<kotlin.version>)[^<]+" ktor-demo/pom.xml)
          echo "KTOR_VERSION=$KTOR" >> $GITHUB_ENV
          echo "KOTLIN_VERSION=$KOTLIN" >> $GITHUB_ENV

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          files: |
            ./quarkus/target/quarkus-demo-1.0.0-SNAPSHOT-runner
            ./micronaut/target/micronaut-demo
            ./spring-boot-web/target/springboot-demo-web
            ./spring-boot-webflux/target/springboot-webflux-demo
            ./vertx/target/vertx-demo
            ./helidon-se-netty/target/helidon-quickstart-se
            ./ktor-demo/target/ktor-${{ env.KTOR_VERSION }}-kotlin-${{ env.KOTLIN_VERSION }}