name: Native CI

on:
  workflow_call:
    inputs:
      files-changed:
        description: 'Files that have changed'
        required: false
        type: string
  push:
    paths:
      - '**/pom.xml'
      - '**/*.java'
      - '**/*.kt'
  pull_request:
    paths:
      - '**/pom.xml'
      - '**/*.java'
      - '**/*.kt'

permissions:
  contents: 'write'
  id-token: 'write'
  packages: 'write'
  deployments: 'write'
  repository-projects: 'write'
  pull-requests: 'write'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        java: [24]
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: ${{ matrix.java }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          distribution: 'graalvm'
      - name: graalvm builds
        run: |
          mvn -ntp package -Pnative -DskipTests -f avaje-jex-jdk/pom.xml

      - uses: marvinpinto/action-automatic-releases@latest
        if: steps.changes.outputs.skip == 'false'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          files: |
            ./avaje-jex-jdk/target/avaje-jex-jdk
            ./quarkus/target/quarkus-demo-runner
            ./micronaut/target/micronaut-demo
            ./spring-boot-web/target/springboot-demo-web
            ./spring-boot-webflux/target/springboot-webflux-demo
            ./vertx/target/vertx-demo
            ./helidon-se-netty/target/helidon-quickstart-se
            ./ktor/target/ktor-demo
