name: Native CI

on:
  workflow_call:
    inputs:
      files-changed:
        description: 'Files that have changed'
        required: false
        type: string
  push:
    paths:
      - '**/pom.xml'
      - '**/*.java'
      - '**/*.kt'
  pull_request:
    paths:
      - '**/pom.xml'
      - '**/*.java'
      - '**/*.kt'

permissions:
  contents: 'write'
  id-token: 'write'
  packages: 'write'
  deployments: 'write'
  repository-projects: 'write'
  pull-requests: 'write'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 120
    strategy:
      matrix:
        java: [25]
    steps:
      - uses: actions/checkout@v4
      - name: Check for relevant file changes
        id: changes
        run: |
          if [ "${{ github.event_name }}" = "workflow_call" ]; then
            echo "skip=false" >> $GITHUB_OUTPUT
          else
            # Check if any pom.xml or Java files have changed
            if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E '\.(java|kt)$|pom\.xml$'; then
              echo "skip=false" >> $GITHUB_OUTPUT
            else
              echo "skip=true" >> $GITHUB_OUTPUT
            fi
          fi
      - uses: graalvm/setup-graalvm@v1
        if: steps.changes.outputs.skip == 'false'
        with:
          version: 'latest'
          java-version: ${{ matrix.java }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          distribution: 'graalvm'
      - name: graalvm builds
        if: steps.changes.outputs.skip == 'false'
        run: |
          mvn -ntp package -Pnative -DskipTests -f avaje-jex-jdk/pom.xml
          mvn -ntp package -Pnative native:compile -DskipTests -f spring-boot-web/pom.xml
          mvn -ntp package -Pnative native:compile -DskipTests -f spring-boot-webflux/pom.xml
          mvn -ntp package -Pnative,native-image -Dpackaging=native-image -DskipTests -f quarkus/pom.xml
          mvn -ntp package -Pnative,native-image -Dpackaging=native-image -DskipTests -f micronaut/pom.xml
          mvn -ntp package -Pnative,native-image -Dpackaging=native-image -DskipTests -f ktor/pom.xml
          mvn -ntp package -Pnative,native-image -Dpackaging=native-image -DskipTests -f helidon-se-netty/pom.xml
          mvn -ntp package -Pnative,native-image -Dpackaging=native-image -DskipTests -f vertx/pom.xml

      - uses: marvinpinto/action-automatic-releases@latest
        if: steps.changes.outputs.skip == 'false'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: latest
          prerelease: true
          title: Development Build
          files: |
            ./avaje-jex-jdk/target/avaje-jex-jdk
            ./quarkus/target/quarkus-demo-runner
            ./micronaut/target/micronaut-demo
            ./spring-boot-web/target/springboot-demo-web
            ./spring-boot-webflux/target/springboot-webflux-demo
            ./vertx/target/vertx-demo
            ./helidon-se-netty/target/helidon-quickstart-se
            ./ktor/target/ktor-demo
