name: Send Mastodon Post

on:
  workflow_run:
    workflows: [ "Run Gatling And Java CI" ]
    types:
      - completed
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  send_mastodon:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Generate URL and send toot to Mastodon
        id: mastodon
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
          && sudo mkdir -p -m 755 /etc/apt/keyrings \
                && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
                && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
          && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
          && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
          && sudo apt update \
          && sudo apt install gh -y

          DATE=$(date +"%Y-%m-%d")
          YEAR=$(date +"%Y")
          JAVA_VERSION=$(grep -oP '(?<=java: \[)\d+(?=\])' .github/workflows/rungatling.yml)
          URL="https://ozkanpakdil.github.io/microservicetests/$YEAR/$DATE-microservice-framework-test-$JAVA_VERSION.html"
          echo "URL=$URL" >> $GITHUB_ENV
          WORKFLOWS=("Run Gatling And Java CI" "Native CI" "Another Workflow")
          RUN_TIMES=""
          for WORKFLOW in "${WORKFLOWS[@]}"; do
            RUN_ID=$(gh api -X GET /repos/${{ github.repository }}/actions/workflows | jq -r ".workflows[] | select(.name==\"$WORKFLOW\") | .id")
            LAST_RUN=$(gh api -X GET /repos/${{ github.repository }}/actions/workflows/$RUN_ID/runs?per_page=1 | jq -r '.workflow_runs[0]')
            START_TIME=$(echo $LAST_RUN | jq -r '.run_started_at')
            END_TIME=$(echo $LAST_RUN | jq -r '.updated_at')
            START_TIMESTAMP=$(date -d "$START_TIME" +%s)
            END_TIMESTAMP=$(date -d "$END_TIME" +%s)
            DURATION=$(date -u -d @$(( END_TIMESTAMP - START_TIMESTAMP )) +%H:%M:%S)
            RUN_TIMES="$RUN_TIMES\n$WORKFLOW: $DURATION"
          done
          echo "RUN_TIMES=$RUN_TIMES" >> $GITHUB_ENV

      - name: Send toot to Mastodon
        uses: cbrgm/mastodon-github-action@v2
        with:
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }} 
          url: ${{ secrets.MASTODON_URL }} 
          message: |
            Latest microservice test framework comparison is released here ${{ env.URL }}
            Last build times:
            ${{ env.RUN_TIMES }} 