name: Run Gatling And Java CI

on:
  workflow_call:

permissions:
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        java: [24]
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: ${{ matrix.java }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          distribution: 'graalvm'
          native-image-job-reports: 'true'
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          cache: 'maven'
          distribution: 'temurin'
      - name: Collect Workflow Telemetry
        uses: catchpoint/workflow-telemetry-action@v2
        with:
          proc_trace_sys_enable: true
          comment_on_pr: false
          theme: dark
      - name: Run jars and get test results
        run: ./runGatling.sh
      - name: Upload test result as artifact
        uses: actions/upload-artifact@v4
        with:
          name: test-result
          path: test-result.md
      - name: Commit the test result
        env:
          TOKEN_GIT: ${{ secrets.TOKEN_GIT }}
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
          set -x
          DATE=$(date +"%Y-%m-%d")
          YEAR=$(date +"%Y")
          git config --global user.email "ozkan.pakdil@gmail.com"
          git config --global user.name "ozkanpakdil"
          rm -rf ozkanpakdil.github.io
          rm -rf page
          git clone https://${TOKEN_GIT}@github.com/ozkanpakdil/ozkanpakdil.github.io.git page
          git config pull.rebase true
          mkdir -p page/content/posts/microservicetests/$YEAR/
          # Check if test-result.md exists before trying to move it
          if [ -f "test-result.md" ]; then
            mv test-result.md page/content/posts/microservicetests/$YEAR/$DATE-microservice-framework-test-${{ matrix.java }}.md
            cd page/content/posts/microservicetests/$YEAR
            git add $DATE-microservice-framework-test-${{ matrix.java }}.md
            # ls -1tr | head -n -10 | xargs -d '\n' git rm -f --
            git commit -m "Automatic publish from micro frameworks test"
            git push
          else
            echo "test-result.md file not found, skipping commit"
          fi
          cd $GITHUB_WORKSPACE
          rm -rf page

